export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const ADD_INGREDIENTS_TO_STORE = 'ADD_INGREDIENTS_TO_STORE';
export const SUM_PRICE = 'SUM_PRICE';
